[package]
name = "cad"
version = "0.0.1"
edition = "2024"
description = "CAD-as-a-library"
license = "MIT"
homepage = "https://libcad.org"
documentation = "https://libcad.org/docs"
repository = "https://github.com/sebhalldesigns/libcad"

[dependencies]
env_logger = "0.11.9"
glam = "0.30.8"
pollster = "0.4.0"
raw-window-handle = "0.6.2"
vello = "0.7.0"
wgpu = "27.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
 
