/***************************************************************
**
** libcad Header File
**
** File         :  object.h
** Module       :  core/object
** Author       :  SH
** Created      :  2026-02-14 (YYYY-MM-DD)
** License      :  MIT
** Description  :  libcad core object type
**
***************************************************************/

#ifndef LIBCAD_CORE_OBJECT_H
#define LIBCAD_CORE_OBJECT_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************************************************
** MARK: INCLUDES
***************************************************************/

#include <model/type/type.h>
#include <jansson.h>

/***************************************************************
** MARK: FORWARD DECLARATIONS
***************************************************************/

typedef struct object_t object_t;
typedef struct object_class_t object_class_t;

/***************************************************************
** MARK: TYPE DEFINITIONS
***************************************************************/

/*
** object_t instance structure - base tree node type
**
** Every object can have children, forming a document tree.
** This enables uniform tree traversal, serialization, and hierarchy management.
**
** IMPORTANT: First field MUST be the class pointer (cls)
**            This is automatically set by type_instance_new()
*/
typedef struct object_t {
    object_class_t* cls;  /* Pointer to class/vtable (set automatically) */

    /* Instance data */
    char* name;
    bool visible;

    /* Tree structure - every object can have children */
    object_t** children;
    size_t children_count;
    size_t children_capacity;
} object_t;

/*
** object_t class structure (vtable + metadata)
**
** This is the "type" - there's one instance of this per type,
** shared by all instances. Contains function pointers (vtable)
** and type metadata.
*/
typedef struct object_class_t {
    type_class_t parent_class;  /* Base class metadata */

    /* Virtual methods - can be overridden by subclasses */
    void (*debug_print)(object_t* self);
    json_t* (*to_json)(object_t* self);

    /* Tree management virtual methods */
    void (*add_child)(object_t* self, object_t* child);
    void (*remove_child)(object_t* self, size_t index);
} object_class_t;

/***************************************************************
** MARK: TYPE SYSTEM
***************************************************************/

/* Get the type handle (auto-registers on first call) */
type_handle_t object_get_type(void);

/* Get the class singleton */
object_class_t* object_class_get(void);

/***************************************************************
** MARK: CONSTRUCTORS
***************************************************************/

/* Create new instance (auto-generated by macro) */
object_t* object_new(void);

/* Destroy instance (auto-generated by macro) */
void object_free(object_t* self);

/***************************************************************
** MARK: PUBLIC API - Properties
***************************************************************/

/* Property accessors */
void object_set_name(object_t* self, const char* name);
const char* object_get_name(const object_t* self);
void object_set_visible(object_t* self, bool visible);
bool object_is_visible(const object_t* self);

/***************************************************************
** MARK: PUBLIC API - Tree Management
***************************************************************/

/* Add a child object to this object's children */
void object_add_child(object_t* self, object_t* child);

/* Remove child at index */
void object_remove_child(object_t* self, size_t index);

/* Get child at index */
object_t* object_get_child(const object_t* self, size_t index);

/* Get number of children */
size_t object_get_child_count(const object_t* self);

/***************************************************************
** MARK: PUBLIC API - Methods
***************************************************************/

/* Methods (these are the default implementations) */
void object_debug_print(object_t* self);
json_t* object_to_json(object_t* self);

/***************************************************************
** MARK: CONVENIENCE MACROS
***************************************************************/

/* Type checking */
#define OBJECT(obj) LIBCAD_CHECK_CAST(obj, object_t, object_get_type)
#define OBJECT_CLASS(cls) LIBCAD_CHECK_CLASS_CAST(cls, object_class_t)
#define IS_OBJECT(obj) (obj && LIBCAD_GET_CLASS(obj) == object_class_get())

/* Polymorphic method calls */
#define OBJECT_DEBUG_PRINT(obj) \
    ((object_class_t*)LIBCAD_GET_CLASS(obj))->debug_print((object_t*)(obj))

#define OBJECT_TO_JSON(obj) \
    ((object_class_t*)LIBCAD_GET_CLASS(obj))->to_json((object_t*)(obj))

#define OBJECT_ADD_CHILD(obj, child) \
    ((object_class_t*)LIBCAD_GET_CLASS(obj))->add_child((object_t*)(obj), (object_t*)(child))

#define OBJECT_REMOVE_CHILD(obj, index) \
    ((object_class_t*)LIBCAD_GET_CLASS(obj))->remove_child((object_t*)(obj), (index))

#ifdef __cplusplus
}
#endif

#endif /* LIBCAD_CORE_OBJECT_H */
